bulletjournal/bulletjournal/urls.py
from django.conf.urls import patterns, include, url
from journal.views import MonthView
from django.contrib.auth.decorators import login_required


urlpatterns = patterns('',

    url(r'^$', login_required(MonthView.as_view()), name='home'),
    url(r'^journal/', include('journal.urls', namespace='journal')),
    
    url(r'^accounts/login/$', 'django.contrib.auth.views.login',
        {'template_name': 'login.html'}, name='login'),

    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout',
        {'template_name': 'logout.html'}, name='logout')

)

bulletjournal/journal/urls.py
from django.conf.urls import patterns, url
from journal.views import UpdateCompletedItemView, ChangeIndicatorForItemView,\
    MonthView, DailyCalendar
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('journal.views',

    url(r'^month_view/$', login_required(MonthView.as_view()), name='month_view'),
    url(r'^daily_calendar/$', login_required(DailyCalendar.as_view()), name='daily_calendar'),
    

    url(r'^item/completed/(?P<pk>\d+)/$', login_required(UpdateCompletedItemView.as_view()), name='update_completed_item'),
    url(r'^item/indicator/(?P<pk>\d+)/$', login_required(ChangeIndicatorForItemView.as_view()), name='update_indicator_item'),

)

bulletjournal/journal/models.py
from django.db import models
from django.conf.global_settings import AUTH_USER_MODEL


class Collection(models.Model):
    name = models.CharField(max_length=255)


class Item(models.Model):

    INDICATORS = (
        ('N', ''),
        ('I', 'Important'),
        ('E', 'Keep an eye'),
        ('D', 'Inspiration')
    )

    collection = models.ForeignKey(Collection, null=True, blank=True)
    date = models.DateField()
    description = models.CharField(max_length=255)
    generated_from = models.ForeignKey('self', null=True, blank=True)
    irrelevant = models.BooleanField(default=False)
    indicator = models.CharField(max_length=1, choices=INDICATORS)
    user = models.ForeignKey(AUTH_USER_MODEL)
    
    def __unicode__(self):
        return self.description
    

class CompletableItem(Item):
    completed = models.BooleanField(default=False)


class Task(CompletableItem):
    father = models.ForeignKey('self', related_name='childs', null=True, blank=True)


class Event(CompletableItem):
    pass


class Note(Item):
    pass

bulletjournal/bulletjournal/views.py
from django.http.response import HttpResponse
import json


class JSONResponseMixin(object):
    """
    A mixin that can be used to render a JSON response.
    """
    def render_to_json_response(self, context, **response_kwargs):
        """
        Returns a JSON response, transforming 'context' to make the payload.
        """
        return HttpResponse(
            self.convert_context_to_json(context),
            content_type='application/json',
            **response_kwargs
        )

    def convert_context_to_json(self, context):
        "Convert the context dictionary into a JSON object"
        # Note: This is *EXTREMELY* naive; in reality, you'll need
        # to do much more complex handling to ensure that arbitrary
        # objects -- such as Django model instances or querysets
        # -- can be serialized as JSON.
        return json.dumps(context)

bulletjournal/journal/views.py
from bulletjournal.views import JSONResponseMixin
from collections import OrderedDict
from django.utils import simplejson
from django.views.generic.base import TemplateView
from django.views.generic.edit import BaseUpdateView
from journal.models import Event, Task, CompletableItem, Item, Note
import calendar
import datetime
from django.db.models import Q
from itertools import chain


class MonthView(TemplateView):
    
    template_name = 'journal/monthview.html'
    
    def get_context_data(self, **kwargs):
        c = TemplateView.get_context_data(self, **kwargs)
        
        today = datetime.date.today()
        c['today'] = today # Added to the context so we can use it in the template
        
        # Query all tasks for the user, only parents, for this month
        c['tasks'] = Task.objects.filter(date__month=today.month,
                                         user=self.request.user,
                                         father__isnull=True)
        
        # Query all events for the user, for this month
        events = Event.objects.filter(date__month=today.month,
                                      user=self.request.user)
        
        # I need to put them under the correct day, so I create an ordered dict, using
        # the days of the month for as keys, and appending the events to the days
        # when the day of the event matches 
        c['events'] = OrderedDict()
        (_, last_day) = calendar.monthrange(today.year, today.month) # First argument discouraged
        
        # Initialize the OrderedDict
        for i in range(0, last_day):
            c['events'][datetime.date(today.year, today.month, i + 1)] = []
        
        # Fill the dict with events
        for event in events:
            c['events'][event.date].append(event)
        
        # returning the context
        return c


class DailyCalendar(TemplateView):
    
    template_name = 'journal/dailycalendar.html'
    
    def get_context_data(self, **kwargs):
        c = TemplateView.get_context_data(self, **kwargs)
        
        today = datetime.date.today()
        c['today'] = today # Added to the context so we can use it in the template
        
        days = OrderedDict()
        c['days'] = days
        
        q = Q(date=today) & Q(user=self.request.user)
        tasks = Task.objects.filter(q).filter(father__isnull=True).all()
        events = Event.objects.filter(q).all()
        notes = Note.objects.filter(q).all()
        
        days[today] = chain(tasks, events, notes) 
        
        print c['days']
        
        return c


class UpdateCompletedItemView(JSONResponseMixin, BaseUpdateView):
    model = CompletableItem

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()

        completed = simplejson.loads(request.POST.get('completed'))
        self.object.completed = completed
        self.object.save()

        return self.render_to_json_response({
            'cod': 1,
            'msg': 'Item updated'
        })


class ChangeIndicatorForItemView(JSONResponseMixin, BaseUpdateView):
    model = Item

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()

        indicator = request.POST.get('indicator')
        self.object.indicator = indicator
        self.object.save()

        return self.render_to_json_response({
            'cod': 1,
            'msg': 'Item Updated'
        })

bulletjournal/bulletjournal/templates/__dummy.html
DUMMIIIIIIIII

bulletjournal/bulletjournal/templates/_base.html
<!DOCTYPE html>
<html>
	<head>
		<title>Bullet Journal - Web</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<link href="{{ STATIC_URL }}bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
		<link href="{{ STATIC_URL }}bootstrap/css/bootstrap-theme.min.css" rel="stylesheet" media="screen">

		<script src="{{ STATIC_URL }}jquery/jquery-2.0.3.min.js"></script>
		<script src="{{ STATIC_URL }}bootstrap/js/bootstrap.min.js"></script>
		
		<script src="{{ STATIC_URL }}jquery/libs/jquery.bootstrap-growl.min.js"></script>
		<script src="{{ STATIC_URL }}jquery/libs/jquery.cookie.js"></script>

		<style>
			body {
				margin-top: 60px;
			}
		</style>
		
		{% block extra_css %}{% endblock %}

	</head>
	<body>

		<header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
			<div class="container">
				<div class="navbar-header">
					<button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a href="../" class="navbar-brand">Bullet Journal</a>
				</div>
				<nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
					<ul class="nav navbar-nav">
						<li>
							<a href="{% url 'journal:month_view' %}">Month View</a>
						</li>
						<li>
							<a href="{% url 'journal:daily_calendar' %}">Daily Calendar</a>
						</li>
					</ul>
				</nav>
			</div>
		</header>

		<div class="container">
			<div class="page-header">
				<h1>{% block title %}{% endblock %} <small>{% block subtitle %}{% endblock %}</small></h1>
			</div>
			{% block content %}{% endblock %}
		</div>
		<footer>
			<div xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/" about="http://bulletjournal.com/">
				<span property="dct:title">Bullet Journal</span> (<a rel="cc:attributionURL" property="cc:attributionName" href="http://bulletjournal.com/www.bulletjournal.com">Ryder Carroll</a>) / <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/">CC BY-NC-SA 3.0</a>
			</div>
		</footer>
	</body>
</html>

bulletjournal/bulletjournal/templates/login.html
{% extends "_base.html" %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action="{% url 'django.contrib.auth.views.login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}

bulletjournal/bulletjournal/templates/logout.html
{% extends "_base.html" %}

{% block content %}
You are logged out!
{% endblock %}

bulletjournal/journal/templates/journal/__day.html
{% load journal_filters %}
<h2>{{ day }}</h2>
{% for item in items %}
	{% render_item item %}
{% endfor %}

bulletjournal/journal/templates/journal/__item.html
<div class="row item {% if item.date < today %}past{% endif %}">
	<div class="col-md-3">
		<div class="input-group">
			<span class="input-group-addon">
				<select class='indicator'
				action="{% url 'journal:update_indicator_item' item.pk %}">
				{% for i in item.INDICATORS %} <option value="{{ i.0 }}" {% ifequal item.indicator i.0 %}selected{% endifequal%}> {{ i.0 }} </option> {% endfor %}
				</select> </span>
			<span class="input-group-addon">
				<input type='checkbox' class="completed" {% if item.completed %}checked{% endif %} id='completed_{{ item.pk }}'
				action="{% url 'journal:update_completed_item' item.pk %}"/>
				<label for="completed_{{ item.pk }}"><span></span></label>
			</span>
		</div><!-- /input-group -->
	</div>
	<div class="col-md-9">
		{{ item }}
	</div>
</div>

bulletjournal/journal/templates/journal/_event.html
{% extends 'journal/__item.html' %}

bulletjournal/journal/templates/journal/_journalbase.html
{% extends '_base.html' %}

{% block extra_css %}
<link href="{{ STATIC_URL }}journal/css/items.css" rel="stylesheet" media="screen">
{% endblock %}

{% block content %}
{{ block.super }}

{% endblock %}

bulletjournal/journal/templates/journal/_task.html
{% extends 'journal/__item.html' %}

bulletjournal/journal/templates/journal/dailycalendar.html
{% extends 'journal/_journalbase.html' %}
{% load journal_filters %}

{% block title %}Daily Calendar{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-6">
		{% for daygroup in days.items %}
			{{ daygroup.0 }}
			{% for item in daygroup.1 %}
			{% render_item item %}
			{% endfor %}
		{% endfor %}
	</div>
	<div class="col-md-6"></div>
</div>
{% endblock %}

bulletjournal/journal/templates/journal/monthview.html
{% extends 'journal/_journalbase.html' %}

{% block title %}{{ today|date:"F Y" }}{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-6">
		<h2>Events</h2>
		{% for day, items in events.items %}
		<div class="row">
			<div class="col-md-1">
				{{ day|date:"d" }}
			</div>
			<div class="col-md-1">
				{{ day|date:"D" }}
			</div>
			<div class="col-md-10">
				{% for e in items %}
					{% include 'journal/_event.html' with item=e %}
				{% endfor %}
			</div>
		</div>
		{% endfor %}
	</div>
	<div class="col-md-6">
		<h2>Tasks</h2>
		{% for task in tasks %}
		{% include 'journal/_task.html' with item=task %}
		{% endfor %}
	</div>
</div>
<script src="{{ STATIC_URL }}journal/js/items.js"></script>
{% endblock %}